// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEELoVsRO-3P_9t6egl-H3Iv86cjk-JsA',
    appId: '1:236713676616:web:1a4c46f8934301aad0ed7d',
    messagingSenderId: '236713676616',
    projectId: 'installmentapp-639b1',
    authDomain: 'installmentapp-639b1.firebaseapp.com',
    storageBucket: 'installmentapp-639b1.firebasestorage.app',
    measurementId: 'G-MBWF94Z0XH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCl1eBz13YIkPGCwgt8Hxhey4HQtSbvRGM',
    appId: '1:236713676616:android:e0301d1d956e1bd9d0ed7d',
    messagingSenderId: '236713676616',
    projectId: 'installmentapp-639b1',
    storageBucket: 'installmentapp-639b1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAB_6tIiljTg9BlQHeAWT7bPNFFKZXqWRE',
    appId: '1:236713676616:ios:acf536bf63fa3cc4d0ed7d',
    messagingSenderId: '236713676616',
    projectId: 'installmentapp-639b1',
    storageBucket: 'installmentapp-639b1.firebasestorage.app',
    iosBundleId: 'com.example.installmentApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAB_6tIiljTg9BlQHeAWT7bPNFFKZXqWRE',
    appId: '1:236713676616:ios:acf536bf63fa3cc4d0ed7d',
    messagingSenderId: '236713676616',
    projectId: 'installmentapp-639b1',
    storageBucket: 'installmentapp-639b1.firebasestorage.app',
    iosBundleId: 'com.example.installmentApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEELoVsRO-3P_9t6egl-H3Iv86cjk-JsA',
    appId: '1:236713676616:web:cb7ea28e6039d003d0ed7d',
    messagingSenderId: '236713676616',
    projectId: 'installmentapp-639b1',
    authDomain: 'installmentapp-639b1.firebaseapp.com',
    storageBucket: 'installmentapp-639b1.firebasestorage.app',
    measurementId: 'G-R0KQ7ER6TX',
  );
}
